# 선형대수 Linear Algebra
- 데이터를 다루기 위한 기술용어
- 복잡한 데이터를 연산에 대한 소통을 간결하고 정확하게

# 함수와 미적분 Funtion and Calculus
- 함수 : 데이터 분석의 결과와 품질을 표현하는 방법
- 예측 문제 : 입력 데이터를 넣으면 원하는 출력 데이터를 만드는 함수 찾기
- 미적분 : 함수의 특징을 기술하는 방법

# 최적화 Optimization
- 최적화 : 가장 좋은 함수의 입력값 혹은 함수를 찾는 작업
- 최적화에는 미분이 필수

# 확률론 Probability
- 데이터분석, 머신러닝은 데이터로부터 지식(명제)를 이끌어내는 작업
- 지식(명제)의 참과 거짓을 다루는 것은 논리학
- 고전 논리학에서 명제는 참(100% 진실) 또는 거짓(0% 진실)
- 확률론에서 명제는 숫자로 표현되는 진실성을 가진다 -> 근대논리학

# 1. 수학기호

- 인사인 수식 
- 디스플레이 수식 
(아래 식 참조)

$\alpha$와 $\beta$의 값이 같다.
$$ \alpha = \beta $$

In [1]:
# 과제 : 전부다 써보기

# 1.2 수열과 집홥의 합과 곱

- x1...xn : 아래 나타내는 숫자는 인덱스(index)라고 한다 : 수열 표시

- {x1...xn} : 중괄호 표시 (순서가 중요하지 않다) : 집합 표시
    - 실수(real number) 의 기호는 R 이라 한다.
    
- $\sum $  : 합
- $\product $  : 곱

# 2. 데이터와 행렬
- import numpy as np // import matplotlib.pylab as plt : 계속 씀

- 스칼라 : 하나의 숫자만으로 이루어진 데이터
- 벡터 : 여러개의 숫자가 특정한 순서대로 모여있는 것 (일반적으로 열벡터를 씀)
    - 예측 문제에서 입력 데이터로 사용되면 특징벡터(feature vector)라 한다.
- 텐서 : 같은 크기의 행렬이 여러개 같이 묶어있는것(3차원 이상)
- 전치연산 : 스칼라, 벡터, 행렬 데이터를 변형시키는 방법(행 과 열이 바뀜)
- 영벡터(zeros-vector) 
- 일벡터(ones-vector)
- 정방행렬(square matrix) 대각행렬(main diagonal) 항등행렬(identity matrix)
- 대칭행렬(symmetricmatrix)

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [7]:
iris.data[0, :]

array([5.1, 3.5, 1.4, 0.2])

In [27]:
x1 = np.array([5.1, 3.5, 1.4, 0.2])
x1

(array([5.1, 3.5, 1.4, 0.2]), array([5.1, 3.5, 1.4, 0.2]))

In [26]:
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2, x2.T

(array([[4.9],
        [3. ],
        [1.4],
        [0.2]]),
 array([[4.9, 3. , 1.4, 0.2]]))

In [29]:
X = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X, X.T, X.T.T

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2]]),
 array([[5.1, 4.9],
        [3.5, 3. ],
        [1.4, 1.4],
        [0.2, 0.2]]),
 array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2]]))

In [35]:
np.zeros((3, 2)), np.ones((3, 2)), np.diag([1, 2, 3]), np.identity(3)

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

# 2.2 벡터와 행렬의 연산

- 모양이 같아야 연산이 가능하다.
- 브로드캐스팅(broadcasting)
- 평균제거(mean removed)벡터 혹은 0-평균(zero-mean)벡터
- 선형조합(linear combination) : 백터/행렬에 스칼라값을 곱한 후 더하거나 뺀 것
- 백터와 벡터의 곱셈(내적, 닷프로덕트) : 두 벡터의 길이는 같아야 한다 / 앞의 벡터가 행벡터 뒤의 벡터가 열 벡터야야 한다.
    - 덧셈은 벡터가되고, 곱셈은 스칼라가 된다
- 가중평균(weighted average) : 전체 가중치의 값의 합으로 나누면 가중평균이 된다.
- 유사도 : 두벡터가 닮은 정도를 정량적으로 나타낸 값 (비슷하면 값이 큼)

In [4]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])
x + y, x - y

(array([10, 12, 14, 16, 18]), array([10, 10, 10, 10, 10]))

In [10]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
x.T @ y, np.dot(x.T, y)

(array([[32]]), array([[32]]))

In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x @ y, np.dot(x, y)

(32, 32)

In [18]:
p = np.array([[100], [80], [50]])
n = np.array([[3], [4], [5]])
p.T @ n, n.T @ p

(array([[870]]), array([[870]]))

In [24]:
from sklearn.datasets import load_digits
data = load_digits()
x = data.data
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [25]:
x[0, :], x[9, :]

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]),
 array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
        13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
        16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
         0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
         9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.]))

In [26]:
x[0, :] @ x[9, :]

2807.0

# 선형회귀 모형(linear regression model)
- x에서 종속변서 y를 예측하는 방법의 하나로 벡터 x와 가중치 벡터 w와의 가중합으로 y에대한 예측값 y^를 계산하는방법
- 단점 : 실제 잘 예측 못함 하지만 기본이되는 모델

# 행렬의 곱셉
- 앞의 열과 뒤의 행이 같아야함

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
A @ B, np.dot(A, B)

(array([[22, 28],
        [49, 64]]),
 array([[22, 28],
        [49, 64]]))

In [19]:
A = np.array([1, 2, 3])
B = np.array([[4, 7], [5, 8], [6, 9]])
A @ B

array([32, 50])

In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B, B @ A

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]))

In [20]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.T @ A, A @ A.T

(array([[35, 44],
        [44, 56]]),
 array([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]]))

# 교환법칙과 분배법칙
- 행렬의 곱셈은 곱하는 행렬의 순서를 바꾸는 교환법칙이 성립하지 않는다. 그러나 덧셈에 대한 분배법칙은 성립한다.

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])
A @ B, B @ A, A @ (B + C), A @ B + A @ C, (A + B).T, A.T + B.T, (A @ B).T, B.T @ A.T

(array([[19, 22],
        [43, 50]]),
 array([[23, 34],
        [31, 46]]),
 array([[42, 42],
        [98, 98]]),
 array([[42, 42],
        [98, 98]]),
 array([[ 6, 10],
        [ 8, 12]]),
 array([[ 6, 10],
        [ 8, 12]]),
 array([[19, 43],
        [22, 50]]),
 array([[19, 43],
        [22, 50]]))

# 곱셈의 연결
- 연속된 행렬의 곱셈은 계산 순서를 임의의 순서로 해도 상관없다.
- 어떤 행렬이든 항등행렬을 곱하면 그 항렬의 값이 변하지 않는다.

In [28]:
A = np.array([1, 2])
B = np.array([[1, 2], [3, 4]])
C = np.array([[5], [6]])
(A @ B) @ C, A @ (B @ C)

(array([95]), array([95]))

In [36]:
A = np.array([[1, 2], [3, 4]])
I = np.eye(2)
A @ I, I @ A       

(array([[1., 2.],
        [3., 4.]]),
 array([[1., 2.],
        [3., 4.]]))

# 행렬과 벡터의 곱
- 열벡터의 선형조합

In [37]:
X = np.array([[1, 2, 3], [4, 5, 6]])
W = np.array([[2], [3], [4]])
X @ W

array([[20],
       [47]])

# 잔차
- 예측치와 실젯값의 차이를 오차 혹은 잔차라고 한다.

# 부분행렬