# 2.3 행렬의 성질
- 부호나 크기를 정의하기 어렵지만 유사한 개념은 정의할 수 있다
- 정부호(positive definite)와 준정부호(positive semi-definite) [x.T A x]


# 행렬 놈(norm) ||A||
- 놈의 값은 0이상이다. 영행렬일 때만 놈의 값이 0이 된다
- 행렬에 스칼라를 곱하면 놈의 값도 그 스칼라의 절대값을 곱한것과 같다
- 행렬의 합의 놈은 각 행렬의 놈의 합보다 작다
- 정방행렬의 곱의 놈은 각 정방행렬의 놈의 곱보다 작다

In [4]:
A = (np.arange(9)-4).reshape(3, 3)
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [5]:
np.linalg.norm(A)

7.745966692414834

# 대각합(trace)
- 정방행렬에 대해서만 정의되며 대각원소의 합으로 계산된다. ex) N차원의 대각합은 N이다

- 스칼라를 곱하면 대각합은 스칼라와 원래의 대각합의 곱이다.
- 전치연산을 해도 대각합의 달라지지 않는다.
- 두 행렬의 합의 대각합은 두 행렬의 대각합의 합이다.
- 두 행렬의 곱은 대각합은 행렬의 순서를 바꾸어도 달라지지 않는다.
- 세 행렬의 곱의 대각합은 다음과 같이 순서를 순호나시켜도달라지지 않는다.

In [7]:
np.trace(np.eye(3))

3.0

# 행렬식(determinant) |A|, det(A)
- 임의의 행하나를 선택하거나 임의의 열 하나를 선택한 다음 이 값에 가중치 를 곱하여 더한것
- 마이너(minor) : 해당 행과 열을 지운 나머지

- 전치 행렬의 행렬식은 원래의 행렬의 행렬식과 같다.
- 항등 해열ㄹ의 행렬식은 1이다.
- 두 행렬의 곱의 행렬식은 각 행렬의 행렬식의 곱과 같다.
- 역행렬은 원래의 행렬과 곱하면 항등행렬이다.
- 역행렬의 행렬식은 원래의 행렬의 행렬식의 역수와 같다.

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

# 선형 연립방정식(system of linear equations)


# 역행렬(inverse matrix)
- 역행렬이 존재하는 행렬을 가역행렬
- 전치행렬의 역행렬은 전치행렬과 같다.
- 두개 이상의 정방행렬의 곱은 같은 크기의 정방행렬이 되는데 이러한 곱의 역행렬은 다음성질이 성립한다.
- 셔먼-모리슨공식, 우드베리공식

# 분할행렬의 역행렬
- 역행렬은 각 분할행렬(partitioned matrix)을 이용하여 계산할수 있다.

In [22]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

# 역행렬과 선형 연립방정식의 해
- 선형 연립방적식에서 미지수의 수와 방정식의 수가 같다면 계수행렬 A는 정방행렬이 된다.

In [24]:
b = np.array([[2], [2], [3]])
x = Ainv @ b
x, A @ x - b

(array([[1.],
        [1.],
        [1.]]),
 array([[0.],
        [0.],
        [0.]]))

In [31]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/Users/itaeu/opt/anaconda3/envs/myconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.],
       [1.],
       [1.]])

# 선형 연립방정식과 선형 예측모형

In [39]:
from sklearn.datasets import load_boston
boston = load_boston()
x = boston.data
y = boston.target
A = x[:4, [0, 4, 5, 6]]   # "CRiM", "NOX", "RM", "AGE"
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [41]:
b = y[:4]
b

array([24. , 21.6, 34.7, 33.4])

In [42]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

- 범죄율에 반비례한다.
- 오염도에 반비례한다.
- 방의 개수에 비례한다.
- 오래된 정도에 반비레한다.

# 미지수의 수와 방정식의 수

# 최소자승문제


In [44]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
b = np.array([[2], [2], [3], [4.1]])
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [47]:
x = Apinv @ b
x, A @ x

(array([[1.03333333],
        [0.95      ],
        [1.05      ]]),
 array([[1.98333333],
        [2.        ],
        [3.03333333],
        [4.08333333]]))

In [50]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

/Users/itaeu/opt/anaconda3/envs/myconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [51]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666698)

In [55]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [56]:
x , resid, rand, s = np.linalg.lstsq(X, y)
x

/Users/itaeu/opt/anaconda3/envs/myconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])