### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산을 해야 합니다.
- 행열 데이터 생성, 수정, 계산등의 빠르게 처리해주는 패키지
    - 특정
        - C, C++ 포트란로 작성
        - 선형대수학을 빠르게 연산
            - 스칼라, 벡터, 매트릭스

In [7]:
import numpy as np

In [ ]:
# 행렬 데이터 생성 
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [16]:
arrary = np.array([1, 2, 3])
type(arrary), arrary

(numpy.ndarray, array([1, 2, 3]))

In [20]:
arrary2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
arrary2, arrary2.ndim, arrary2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [25]:
# 행렬의 모양(shape) 변경3, 2, 1기
arrary2.reshape(3, 2), arrary2.reshape(6), arrary2.reshape(3, 2, 1)

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[[1],
         [2]],
 
        [[3],
         [4]],
 
        [[5],
         [6]]]))

In [ ]:
# 행렬 데이터의 선택 : offset index : masking

In [30]:
arrary2[1], arrary2[1][2], arrary2[1, 2], arrary2[1][::-1]

(array([4, 5, 6]), 6, 6, array([6, 5, 4]))

In [ ]:
# 데이터 수정

In [32]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [36]:
arrary2[1][2] = 10
arrary2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [37]:
# 브로드 캐스팅
arrary2[0] = 0
arrary2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [38]:
arrary2[0] = [7, 8, 9]
arrary2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [39]:
# 조건으로 선택
arrary2 > 7

array([[False,  True,  True],
       [False, False,  True]])

In [41]:
idx = arrary2 > 7
arrary2[idx]

array([ 8,  9, 10])

In [42]:
arrary2[idx] = 100
arrary2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [ ]:
# 행렬 데이터의 생성 2

In [43]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
data.dtype

dtype('float64')

In [46]:
data2 = data.astype("int")
data2.dtype

dtype('int64')

In [48]:
data = np.ones((2, 3, 2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [49]:
# arange 
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [ ]:
# varince code(분산)

In [16]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])
data3 = np.array([80, 85, 100, 90, 95])
data4 = np.array([100, 90, 70, 90, 80])
data5 = np.array([800, 850, 1000, 900, 950])
data6 = np.array([1000, 900, 700, 900, 800])

In [4]:
def variance(data):
    avg = np.average(data)
    var = 0
    for num in data:
        var += (num - avg) ** 2
    return var / len(data)

In [7]:
variance(data1), variance(data2), variance(data1)**0.5, variance(data2)**0.5

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [8]:
np.var(data1), np.var(data2), np.std(data1), np.std(data2) # 표준편차

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [ ]:
# covariance(공분산)

In [ ]:
# (파이썬은 연습해보기)

In [20]:
np.cov(data1, data2)[0, 1],\
np.cov(data3, data4)[0, 1], \
np.cov(data5, data6)[0, 1]

(93.75, -87.5, -8750.0)

In [ ]:
# correlation coefficient(상관계수)

In [19]:
np.corrcoef(data1, data2)[0, 1],\
np.corrcoef(data3, data4)[0, 1],\
np.corrcoef(data5, data6)[0, 1]

(0.9449111825230682, -0.970725343394151, -0.970725343394151)

In [ ]:
# cofficient of determination : R-squared (결정계수)

In [21]:
np.corrcoef(data1, data2)[0, 1]**2,\
np.corrcoef(data1, data4)[0, 1]**2

(0.892857142857143, 0.9423076923076923)

In [3]:
import pandas as pd

In [16]:
!ls datas

2014_p.csv        2014_s.csv        premierleague.csv train.csv


In [17]:
df = pd.read_csv("datas/premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [23]:
# 득점
gf = np.array(df["gf"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31])

In [24]:
# 실점
ga = np.array(df["ga"])
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56])

In [25]:
# 승정
points = np.array(df["points"])
points

array([100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
        41,  40,  37,  36,  33,  33,  31])

In [27]:
data1, data2 = np.corrcoef(gf, points)[0, 1]**2, np.corrcoef(ga, points)[0, 1]**2
data1, data2

(0.8683266496886471, 0.757933920368845)

In [28]:
round(data1, 2), round(data2, 2)

(0.87, 0.76)