### Numpy
- 데이터는 행열로 표현
- 행열 데이터 빠르게 계산을 해야 합니다.
- 행열 데이터 생성, 수정, 계산등의 빠르게 처리해주는 패키지
    - 특정
        - C, C++ 포트란로 작성
        - 선형대수학을 빠르게 연산
            - 스칼라, 벡터, 매트릭스

In [15]:
import numpy as np

In [ ]:
# 행렬 데이터 생성 
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [16]:
arrary = np.array([1, 2, 3])
type(arrary), arrary

(numpy.ndarray, array([1, 2, 3]))

In [20]:
arrary2 = np.array(
    [[1, 2, 3],
    [4, 5, 6]]
)
arrary2, arrary2.ndim, arrary2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [25]:
# 행렬의 모양(shape) 변경3, 2, 1기
arrary2.reshape(3, 2), arrary2.reshape(6), arrary2.reshape(3, 2, 1)

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[[1],
         [2]],
 
        [[3],
         [4]],
 
        [[5],
         [6]]]))

In [ ]:
# 행렬 데이터의 선택 : offset index : masking

In [30]:
arrary2[1], arrary2[1][2], arrary2[1, 2], arrary2[1][::-1]

(array([4, 5, 6]), 6, 6, array([6, 5, 4]))

In [ ]:
# 데이터 수정

In [32]:
ls = [1, 2, 3]
ls[1] = 5
ls

[1, 5, 3]

In [36]:
arrary2[1][2] = 10
arrary2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [37]:
# 브로드 캐스팅
arrary2[0] = 0
arrary2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [38]:
arrary2[0] = [7, 8, 9]
arrary2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [39]:
# 조건으로 선택
arrary2 > 7

array([[False,  True,  True],
       [False, False,  True]])

In [41]:
idx = arrary2 > 7
arrary2[idx]

array([ 8,  9, 10])

In [42]:
arrary2[idx] = 100
arrary2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [ ]:
# 행렬 데이터의 생성 2

In [43]:
data = np.zeros((2, 3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
data.dtype

dtype('float64')

In [46]:
data2 = data.astype("int")
data2.dtype

dtype('int64')

In [48]:
data = np.ones((2, 3, 2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [49]:
# arange 
np.arange(5)

array([0, 1, 2, 3, 4])

In [50]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(5, 10, 2)

array([5, 7, 9])