# summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 : ndarray, np.array(iterable)
- 행열의 생성 : ones, zeros
- 행열 데이터 선택 : array[x, y, z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range : 결과가 ndarray

In [ ]:
### quiz 
- 100 ~ 130까지 랜덤한 숫자를 가지는 8*8행렬을 만들고
- 3의 배수는 fiz, 5의배수는 buz, 3과 5의 배수는 fbz문자로 변환
- 조건에 맞지않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터
'''
datas = np.random.randint(100, 130, size=(8, 8))
'''
- 데이터 타입이 정수, 실수 : ndarray.astype()

In [2]:
import numpy as np 

datas = np.random.randint(100, 130, size=(8, 8))
datas

array([[118, 100, 106, 103, 127, 127, 107, 112],
       [103, 109, 110, 104, 112, 109, 128, 126],
       [122, 116, 125, 120, 100, 127, 126, 115],
       [117, 105, 119, 125, 106, 128, 107, 100],
       [102, 101, 118, 117, 119, 127, 105, 111],
       [128, 112, 111, 116, 111, 104, 106, 111],
       [104, 101, 114, 110, 122, 120, 129, 128],
       [112, 124, 105, 124, 100, 103, 116, 128]])

In [3]:
data1 = np.array([1, 2, 3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [6]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0 
idx_5 = datas % 5 == 0 
idx_15 = datas % 15 == 0 

In [7]:
# 데이터의 타입을 str으로 변환
datas.dtype

dtype('int64')

In [8]:
result = datas.astype("str")
result

array([['127', '128', '121', '116', '129', '116', '100', '129'],
       ['122', '126', '121', '121', '105', '108', '123', '100'],
       ['126', '111', '120', '107', '128', '102', '111', '115'],
       ['107', '104', '128', '124', '108', '117', '126', '126'],
       ['110', '129', '103', '127', '121', '112', '129', '103'],
       ['127', '100', '111', '103', '108', '128', '118', '103'],
       ['116', '113', '129', '116', '101', '121', '100', '114'],
       ['104', '109', '123', '129', '129', '128', '129', '101']],
      dtype='<U21')

In [ ]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [9]:
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fuz"

In [10]:
result

array([['127', '128', '121', '116', 'fiz', '116', 'buz', 'fiz'],
       ['122', 'fiz', '121', '121', 'fuz', 'fiz', 'fiz', 'buz'],
       ['fiz', 'fiz', 'fuz', '107', '128', 'fiz', 'fiz', 'buz'],
       ['107', '104', '128', '124', 'fiz', 'fiz', 'fiz', 'fiz'],
       ['buz', 'fiz', '103', '127', '121', '112', 'fiz', '103'],
       ['127', 'buz', 'fiz', '103', 'fiz', '128', '118', '103'],
       ['116', '113', 'fiz', '116', '101', '121', 'buz', 'fiz'],
       ['104', '109', 'fiz', 'fiz', 'fiz', '128', 'fiz', '101']],
      dtype='<U21')

In [ ]:
### quiz
- 1 ~ 20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수
'''
np.min(ndarray), np.max(ndarray)
'''

In [13]:
datas = np.random.randint(1, 20, (5, 5))
datas

array([[ 3, 10, 12, 19,  8],
       [16, 19, 18, 18, 13],
       [ 9,  8, 19, 18, 19],
       [ 9, 11, 16,  8,  6],
       [16, 10, 13,  3, 11]])

In [14]:
min_num, max_num = np.min(datas), np.max(datas)
min_num, max_num

(3, 19)

In [15]:
idx_min = datas == min_num
idx_max = datas == max_num

In [16]:
result = datas.astype("str")
result

array([['3', '10', '12', '19', '8'],
       ['16', '19', '18', '18', '13'],
       ['9', '8', '19', '18', '19'],
       ['9', '11', '16', '8', '6'],
       ['16', '10', '13', '3', '11']], dtype='<U21')

In [17]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"

In [18]:
result

array([['MIN', '10', '12', 'MAX', '8'],
       ['16', 'MAX', '18', '18', '13'],
       ['9', '8', 'MAX', '18', 'MAX'],
       ['9', '11', '16', '8', '6'],
       ['16', '10', '13', 'MIN', '11']], dtype='<U21')

In [ ]:
# linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할안 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [3]:
# linspace // 등분
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [4]:
# logspccd // log10(x1)=2,log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [ ]:
### 30세에 연봉이 $100000 이고 60세의 연봉이 $1000000 일때
### 연봉이 선형으로 증가, 지수함수로 증가하는 두경우에서의 40세, 50세 연봉을 출력

In [5]:
age_30 = 100000
age_60 = 1000000

In [6]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [8]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

In [ ]:
### numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 난수를 발생
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어 줍니다. 
- choice : 특정 확률로 데이터를 선택

In [13]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [14]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [15]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [23]:
# shuffle
r= np.random.randint(1, 10, (3, 4))
r

array([[7, 5, 6, 9],
       [4, 1, 1, 6],
       [8, 6, 1, 9]])

In [24]:
np.random.shuffle(r)
r

array([[4, 1, 1, 6],
       [7, 5, 6, 9],
       [8, 6, 1, 9]])

In [25]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([3, 4, 3, 3, 2, 4, 0, 4, 2, 2])

In [28]:
# nuique
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[1 4 5 6 7 8 9]
[3 1 1 3 1 1 2]


In [ ]:
# 행렬 데이터의 결합
- concatenate

In [13]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
data = pd.Series(np.random.randint(1, 10, size=5), index=list("ABCDE"))

In [3]:
data

A    6
B    1
C    4
D    4
E    8
dtype: int64

In [4]:
result = data + 2

In [5]:
result["B"] = 10

In [6]:
result = result + 3

In [7]:
result["B"]

13

In [ ]:
# 세로 결합

In [10]:
na1

array([[9, 3, 5],
       [2, 4, 7]])

In [11]:
na2

array([[6, 8],
       [8, 1],
       [6, 7]])

In [14]:
na3

array([[3, 3, 7],
       [0, 1, 9],
       [9, 0, 4]])

In [15]:
# 세로 결합
np.concatenate((na1, na3))

array([[9, 4, 3],
       [0, 3, 5],
       [3, 3, 7],
       [0, 1, 9],
       [9, 0, 4]])

In [17]:
# 가로 결합
np.concatenate((na2, na3), axis=1)

array([[0, 2, 3, 3, 7],
       [3, 8, 0, 1, 9],
       [1, 3, 9, 0, 4]])

In [18]:
# c_, r_
np.c_[np.array([1,2,4]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [4, 6]])

In [19]:
np.r_[np.array([1,2,4]), np.array([4,5,6])]

array([1, 2, 4, 4, 5, 6])